const CACHE="florence-static-20260809-mobile-main-stability-1";
const CORE_FIX="./core-ui-fixes-v3.js?v=20260809-mobile-main-stability-1";
const DEPUTY_UI="./deputy-integration.js?v=20260809-mobile-main-stability-1";
const INVOICE_UI="./invoicing-workspace.js?v=20260804-pricing-1";
const INVOICE_LOADER="./invoice-menu-fix.js?v=20260804-pricing-1";
const SHELL=["./styles.css?v=20260805-daily-delivery-1","./config.js?v=20260809-mobile-main-stability-1","./app.js?v=20260807-evidence-page-2","./operations.js?v=20260809-mobile-main-stability-1","./staff-management.js?v=20260801-1","./setup-code-display.js?v=20260802-4","./live-refresh-controls.js?v=20260802-2","./notification-navigation.js?v=20260802-2",CORE_FIX,DEPUTY_UI,INVOICE_UI,INVOICE_LOADER,"./core-ui-fixes-v2.js?v=20260809-mobile-main-stability-1","./portal-participant-label.js?v=20260802-2","./portal-care-plan.js?v=20260809-mobile-main-stability-1","./participant-file.js?v=20260809-mobile-main-stability-1","./secure-document-careplan-fix.js?v=20260809-mobile-main-stability-1","./participant-edit-controls.js?v=20260809-mobile-main-stability-1","./medication-prn-fix.js?v=20260806-prn-signing-1","./regular-medication-tab.js?v=20260804-7","./florence-readiness-controls.js?v=20260802-1","./remote-s8-verification.js?v=20260809-mobile-main-stability-1","./sil.css?v=20260807-evidence-page-2","./sil.js?v=20260807-evidence-page-2","./sil-record.js?v=20260807-evidence-page-2","./manifest.webmanifest","./florence-icon.svg","./florence-icon-192.png","./florence-icon-512.png"];
self.addEventListener("install",event=>event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(SHELL)).then(()=>self.skipWaiting())));
self.addEventListener("activate",event=>event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim())));
self.addEventListener("fetch",event=>{
 if(event.request.method!=="GET")return;
 const url=new URL(event.request.url);if(url.origin!==self.location.origin)return;
 if(event.request.mode==="navigate"||["/set-password","/set-password.html","/sil","/sil.html","/sil-record","/sil-record.html"].includes(url.pathname))return;
 event.respondWith((async()=>{try{const response=await fetch(event.request,{cache:"no-store"});if(response.ok){const copy=response.clone();event.waitUntil(caches.open(CACHE).then(cache=>cache.put(event.request,copy)))}return response}catch(_error){const hit=await caches.match(event.request);if(hit)return hit;return new Response("Florence is temporarily offline.",{status:503,headers:{"Content-Type":"text/plain; charset=utf-8"}})}})());
});
self.addEventListener("push",event=>{let payload={title:"Florence",body:"A new Florence alert is available.",url:"./",tag:"florence-alert"};try{if(event.data)payload={...payload,...event.data.json()}}catch(_error){}event.waitUntil(self.registration.showNotification(payload.title,{body:payload.body,icon:"./florence-icon.svg",badge:"./florence-icon.svg",tag:payload.tag,renotify:true,data:{url:payload.url||"./"}}));});
self.addEventListener("notificationclick",event=>{event.notification.close();const target=new URL(event.notification.data?.url||"./",self.location.origin).href;event.waitUntil(clients.matchAll({type:"window",includeUncontrolled:true}).then(windows=>{for(const client of windows){if("focus" in client){client.navigate(target);return client.focus()}}return clients.openWindow?clients.openWindow(target):undefined}));});
