(()=>{
"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],KEY="florence-sil-v1";
const PROVIDER={legalName:"I-Care Connect PTY LTD",abn:"55 699 493 457",address:"1387 Amiens Rd, Amiens, QLD 4380",registrationGroup:"0138 — Assistance with Supported Independent Living",jurisdiction:"Queensland, Australia",keyManagementPersonnel:"Victoria Kussrow",seniorWorker:"Candice Long",reviewCycle:"At least annually, and earlier following legislative, service or risk changes",houseSafeguardingReview:"Every 6 months, after a significant incident, household change or environmental change",houseMeetingFrequency:"At least monthly and whenever a proposed change affects the home",recordRetention:"Retain in accordance with NDIS, privacy, incident and employment obligations",status:"Provider details pre-filled — verify registration and contact details before audit"};
const templates=[
["Policy","SIL Service Delivery and Practice Governance Policy","Annual"],["Policy","SIL Safeguarding Policy","Annual"],["Policy","SIL Supported Decision-Making Policy","Annual"],["Policy","SIL Tenancy, Housing and Support Arrangements Policy","Annual"],["Guidance","SIL Visitor and Private Space Guidance","Annual"],["Agreement","SIL Service Agreement","Per participant / on change"],["Agreement","SIL Tenancy or Occupancy Agreement","Per resident / on change"],["Agreement","SDA and SIL Collaboration Agreement","Per partner / on change"],["Form","SIL Participant Agreement Explanation Record","At commencement / agreement change"],["Form","SIL House Safeguarding Assessment","6-monthly and event-triggered"],["Form","SIL Co-Tenant Compatibility and Risk Review","Before placement"],["Form","SIL Conflict of Interest Review — Housing and Support Overlap","Per participant / annual review"],["Form","SIL House Meeting and Participant Consultation Record","Monthly / event-triggered"],["Form","SIL House Rules and Shared Space Consultation Record","At establishment / change"],["Form","SIL House Visitor and Contractor Log","Ongoing"],["Form","SIL Shift Handover Form","Every shift"],["Workforce","SIL Worker House Induction Checklist","Before first shift / material change"],["Workforce","SIL Worker Competency Checklist","Before unsupervised work / refresher"],["Workforce","SIL Worker Training and Competency Register","Ongoing / 6-month review"],["Workforce","SIL Practice Observation Checklist","As scheduled / concern-triggered"],["Position description","Disability Support Worker (SIL)","At engagement / role change"],["Position description","SIL Team Leader / House Coordinator","At engagement / role change"]
];
const schemas={
house:{title:"Add SIL home",category:"SIL home",help:"Create the property record first. Do not enter tenancy terms or resident decisions unless they are confirmed.",fields:[["name","House name / identifier"],["address","Property address"],["housing_provider","Housing / SDA provider","text",false],["landlord_contact","Landlord or SDA contact","text",false],["bedrooms","Number of bedrooms","number",false],["support_model","Support model","select",["24-hour support","Sleepover","Active night","Drop-in / scheduled","Other"]],["emergency_plan","Emergency and continuity arrangements","textarea",false],["status","Status","select",["Active","Planned","Inactive"]]]},
safeguarding:{title:"House safeguarding assessment",category:"House safeguarding",help:"Assess shared-living, environmental, visitor and worker-practice risks. High risks require immediate action.",fields:[["house","SIL home"],["assessment_date","Assessment date","date"],["risk_level","Overall risk","select",["Low","Medium","High"]],["shared_living_risks","Shared-living and participant-to-participant risks","textarea"],["environmental_risks","Property and environmental risks","textarea"],["visitor_risks","Visitor or third-party risks","textarea",false],["worker_practice_risks","Worker-practice risks","textarea",false],["controls","Controls and safeguarding actions","textarea"],["responsible_person","Responsible person"],["next_review","Next review date","date"]]},
meeting:{title:"House meeting / participant consultation",category:"Consultation",help:"Record each participant’s own view and communication support. House rules and material changes must not be imposed without genuine consultation.",fields:[["house","SIL home"],["meeting_date","Meeting date","datetime-local"],["participants","Participants consulted"],["communication_support","Communication supports used","textarea",false],["topics","Topics discussed","textarea"],["views","Participant views, including disagreement","textarea"],["decisions","Decisions made","textarea",false],["actions","Actions, owners and due dates","textarea",false],["facilitator","Facilitator"]]},
houseRules:{title:"House rules and shared-space consultation",category:"House governance",help:"Rules must preserve each resident’s visitor, privacy, possessions and daily-choice rights.",fields:[["house","SIL home"],["consultation_date","Consultation date","date"],["participants","Participants consulted"],["proposed_rules","Rules or shared-space arrangements discussed","textarea"],["individual_views","Each participant’s views","textarea"],["agreed_rules","Agreed rules","textarea"],["unresolved_concerns","Unresolved concerns","textarea",false],["review_date","Review date","date"]]},
compatibility:{title:"Co-tenant compatibility and risk review",category:"Compatibility",help:"Complete before placement and retain in the house file and each affected participant file.",fields:[["house","SIL home"],["proposed_participant","Proposed participant"],["existing_residents","Existing residents consulted"],["assessment_date","Assessment date","date"],["compatibility_summary","Routine, communication, sleep, mobility, culture and shared-resource compatibility","textarea"],["participant_views","Existing participants’ views","textarea"],["risk_level","Risk level","select",["Low","Medium","High"]],["controls","Safeguarding controls / placement conditions","textarea",false],["decision","Placement decision","select",["Pending","Suitable","Suitable with conditions","Not suitable"]],["approved_by","Approved by","text",false],["review_date","Post-placement review date","date",false]]},
visitor:{title:"Visitor / contractor log",category:"Visitors",help:"This is a safeguarding and transparency record, not an approval register. Participants retain the right to invite visitors.",fields:[["house","SIL home"],["participant","Participant host / person affected","text",false],["visitor_name","Visitor or contractor name"],["visitor_type","Type","select",["Personal visitor","External support worker","Contractor","Volunteer","Health professional","Other"]],["arrival","Arrival","datetime-local"],["departure","Departure","datetime-local",false],["purpose","Purpose / work completed","textarea",false],["awareness","Participant awareness and consent confirmed","select",["Yes","Not applicable","Needs follow-up"]],["notes","Safeguarding or privacy notes","textarea",false]]},
conflict:{title:"Housing-support conflict review",category:"Conflict of interest",help:"Required where I-Care Connect or a related entity is involved in both housing and SIL support.",fields:[["participant","Participant"],["house","SIL home"],["housing_entity","Housing entity"],["support_entity","Support provider","text",false],["overlap","Nature of overlap / relationship","textarea"],["participant_informed","How the participant was informed","textarea"],["independent_choice","How independent provider choice is protected","textarea"],["housing_security","How housing is protected if support changes","textarea"],["controls","Conflict controls","textarea"],["review_date","Review date","date"],["approved_by","Key Management Personnel approval","text",false]]},
communication:{title:"Communication & decision-making profile",category:"Participant profile",help:"Use the participant’s words and preferred communication. Record substituted decision-makers only where legally authorised.",fields:[["participant","Participant"],["preferred_communication","Preferred communication methods","textarea"],["understanding_support","How information should be explained","textarea"],["decision_support","Support needed to make decisions","textarea"],["trusted_people","Trusted supporters / advocates","textarea",false],["authorised_decision_maker","Legally authorised decision-maker and scope","textarea",false],["do_not_assume","Things workers must not assume","textarea",false],["review_date","Review date","date"]]},
instructions:{title:"Participant-specific worker instructions",category:"Participant instructions",help:"Record only current, authorised instructions needed for safe and consistent support.",fields:[["participant","Participant"],["house","SIL home"],["routines","Preferred routines and daily choices","textarea"],["personal_care","Personal-care preferences","textarea",false],["meals","Meal and food preferences","textarea",false],["community","Community and relationship supports","textarea",false],["health_safety","Health and safety instructions","textarea",false],["behaviour_support","Behaviour Support Plan / restrictive-practice alerts","textarea",false],["privacy","Privacy, visitors and private-space preferences","textarea",false],["review_date","Review date","date"]]},
choice:{title:"Participant choice & daily life record",category:"Supported decision-making",help:"Evidence the options, communication support and participant’s own choice. Do not use this to seek provider permission for ordinary life decisions.",fields:[["participant","Participant"],["house","SIL home","text",false],["date","Date and time","datetime-local"],["decision","Decision being made"],["options","Options explained","textarea"],["support","Communication / decision support provided","textarea",false],["choice","Participant’s choice","textarea"],["risk","Identified risk and dignity-of-risk response","textarea",false],["outcome","Outcome / follow-up","textarea",false],["worker","Worker recording"]]},
agreementExplanation:{title:"Agreement explanation record",category:"Participant agreement",help:"Record how the SIL service agreement and tenancy/occupancy agreement were explained accessibly and separately.",fields:[["participant","Participant"],["date","Explanation date","date"],["documents","Documents explained","select",["SIL Service Agreement","Tenancy / Occupancy Agreement","Both agreements"]],["format","Accessible format / communication support","textarea"],["separation_explained","How housing and support separation was explained","textarea"],["rights_understood","Participant’s questions and demonstrated understanding","textarea"],["support_person","Support person / advocate present","text",false],["confirmation","Participant confirmation / signature status","select",["Signed","Verbal confirmation recorded","Awaiting signature","Further explanation required"]]]},
serviceAgreement:{title:"SIL service agreement register",category:"Participant agreement",help:"This register does not replace the signed agreement. Attach the executed agreement in Florence’s Compliance Centre.",fields:[["participant","Participant"],["commencement","Commencement date","date"],["review_date","Review date","date"],["signed_status","Status","select",["Draft","Provided for review","Signed","Expired / replaced"]],["support_scope","Agreed SIL support scope","textarea"],["fees_reference","Pricing / schedule reference","textarea",false],["termination_terms","Termination / change arrangements confirmed","textarea",false],["document_location","Signed document location or reference","text",false]]},
tenancy:{title:"Tenancy / occupancy register",category:"Housing agreement",help:"Do not invent rent, bond, notice periods or legal terms. These must come from the lawful tenancy or occupancy agreement.",fields:[["participant","Resident"],["house","Property"],["housing_provider","Housing provider / landlord"],["commencement","Commencement date","date"],["agreement_type","Agreement type","select",["Residential tenancy agreement","Occupancy agreement","SDA service agreement","Other / legal advice required"]],["rent","Rent / contribution — confirmed amount","text",false],["support_separate","Support arrangement recorded as separate","select",["Yes","Needs confirmation"]],["status","Status","select",["Draft","Signed","Needs legal review","Expired / ended"]],["document_location","Executed document location","text",false]]},
rights:{title:"Welcome & rights acknowledgement",category:"Participant rights",help:"Record provision of rights information in a form the participant can understand.",fields:[["participant","Participant"],["date","Date provided","date"],["format","Format / communication method"],["topics","Rights explained","textarea"],["advocacy","Advocacy and complaint options explained","textarea"],["questions","Questions / concerns raised","textarea",false],["acknowledgement","Acknowledgement status","select",["Signed","Verbal acknowledgement","Further support required"]]]},
privateSpace:{title:"Visitor & private-space preferences",category:"Participant rights",help:"A participant’s SIL home is their home. Preferences support privacy and safeguarding; they are not provider permission conditions.",fields:[["participant","Participant"],["house","SIL home"],["visitor_preferences","Visitor preferences","textarea"],["private_space","Private-space and room-access preferences","textarea"],["keys_possessions","Keys and possessions arrangements","textarea",false],["relationships","Relationship and privacy supports","textarea",false],["co_tenant_balance","How competing co-tenant needs will be managed","textarea",false],["review_date","Review date","date"]]},
handover:{title:"SIL shift handover",category:"Shift handover",help:"Complete at the end of every shift. Record facts and direct observations, not assumptions.",fields:[["house","SIL home"],["shift_date","Shift date","date"],["shift_start","Shift start","time",false],["shift_end","Shift end","time",false],["outgoing_worker","Outgoing worker"],["incoming_worker","Incoming worker"],["wellbeing","Participant wellbeing and significant observations","textarea"],["daily_support","Meals, personal care, activities and choices","textarea",false],["medication","Medication matters","textarea",false],["incidents","Incidents, behaviours or safeguarding concerns","textarea",false],["appointments","Appointments / upcoming activities","textarea",false],["household","Household, maintenance and visitor matters","textarea",false],["actions","Outstanding actions","textarea",false],["incoming_acknowledged","Incoming worker acknowledgement","select",["Acknowledged","Awaiting acknowledgement"]]]},
induction:{title:"SIL worker house induction",category:"Worker induction",help:"Must be completed before the worker’s first shift at the property and repeated after material changes.",fields:[["worker","Worker"],["house","SIL home"],["date","Induction date","date"],["participants_reviewed","Participant profiles and instructions reviewed","select",["Yes","Partly — follow-up required","No"]],["emergency_reviewed","Emergency and continuity arrangements reviewed","select",["Yes","No"]],["safeguarding_reviewed","Safeguarding and house risks reviewed","select",["Yes","No"]],["medication_reviewed","Medication arrangements reviewed","select",["Yes","Not applicable","No"]],["house_practice","House routines, privacy and visitor rights reviewed","select",["Yes","No"]],["gaps","Gaps / supervised practice required","textarea",false],["supervisor","Supervisor / Team Leader"]]},
competency:{title:"SIL worker competency",category:"Worker competency",help:"Competency should be assessed, not assumed from attendance alone.",fields:[["worker","Worker"],["assessment_date","Assessment date","date"],["assessor","Assessor"],["area","Competency area","select",["Participant rights and choice","Supported decision-making","Active support","Safeguarding","Medication","Incident response","Documentation and handover","Positive behaviour support","Emergency response","SIL overall practice"]],["method","Assessment method","select",["Observed practice","Knowledge questions","Scenario assessment","Document review","Combined assessment"]],["outcome","Outcome","select",["Competent","Competent with development actions","Not yet competent"]],["evidence","Evidence and observations","textarea"],["actions","Development / supervision actions","textarea",false],["refresher_due","Refresher due","date",false]]},
training:{title:"SIL training register entry",category:"Worker training",help:"Training attendance and competency are separate. Record assessment outcome where applicable.",fields:[["worker","Worker"],["topic","Training topic"],["completed","Completion date","date"],["method","Delivery method"],["trainer","Trainer / provider"],["outcome","Competency outcome","select",["Completed — competency verified","Completed — assessment pending","Further training required"]],["refresher_due","Refresher due","date",false],["notes","Notes","textarea",false]]},
observation:{title:"SIL practice observation",category:"Practice observation",help:"Use factual observations and discuss findings with the worker.",fields:[["worker","Worker"],["house","SIL home"],["date","Observation date","date"],["observer","Observer"],["areas","Practice areas observed","textarea"],["strengths","Strengths observed","textarea"],["concerns","Concerns / non-conformities","textarea",false],["participant_rights","Participant rights, dignity and choice findings","textarea"],["actions","Actions, owner and due date","textarea",false],["outcome","Outcome","select",["Satisfactory","Development actions","Immediate escalation required"]]]},
provider:{title:"Edit provider profile",category:"Provider governance",help:"Verify these details against current registration and corporate records before an audit.",fields:[["legalName","Legal name"],["abn","ABN"],["address","Business address"],["registrationGroup","SIL registration group"],["keyManagementPersonnel","Key Management Personnel"],["seniorWorker","Senior worker / operational contact","text",false],["reviewCycle","Policy review cycle"],["status","Verification status","textarea"]]}
};
let state=load(),activeTab="dashboard";
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{provider:PROVIDER,records:[]}}catch{return{provider:PROVIDER,records:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render();toast("SIL record saved")}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function toast(t){const e=$("#sil-toast");e.textContent=t;e.classList.add("show");setTimeout(()=>e.classList.remove("show"),2400)}
function uid(){return crypto.randomUUID?.()||Date.now()+"-"+Math.random().toString(16).slice(2)}
function statusOf(r){if(r.status)return r.status;if(r.fields?.next_review&&new Date(r.fields.next_review)<new Date())return"Overdue";const vals=Object.values(r.fields||{});return vals.some(v=>/to be completed|needs confirmation|awaiting/i.test(String(v)))?"Needs confirmation":"Complete"}
function badge(s){const c=/overdue|not yet|high|immediate/i.test(s)?"red":/draft|pending|needs|awaiting|medium/i.test(s)?"amber":"good";return`<span class="badge ${c}">${esc(s)}</span>`}
function fmt(v){if(!v)return"";const d=new Date(v);return isNaN(d)?v:new Intl.DateTimeFormat("en-AU",{day:"numeric",month:"short",year:"numeric",hour:v.includes?.("T")?"numeric":undefined,minute:v.includes?.("T")?"2-digit":undefined}).format(d)}
function fieldHtml(f){const [name,label,type="text",opts=[],required=true]=f,req=required?" required":"",hint=required?"":" <small>(optional)</small>";if(type==="textarea")return`<label>${label}${hint}<textarea name="${name}"${req}></textarea></label>`;if(type==="select")return`<label>${label}${hint}<select name="${name}"${req}><option value="">Select…</option>${opts.map(o=>`<option>${esc(o)}</option>`).join("")}</select></label>`;return`<label>${label}${hint}<input name="${name}" type="${type}"${req}></label>`}
function openForm(type){const s=schemas[type];if(!s)return;$("#sil-dialog-title").textContent=s.title;$("#sil-dialog-help").innerHTML=`${esc(s.help)}<div class="sil-required-note">Fields without “optional” must be completed before saving.</div>`;$("#sil-dialog-fields").innerHTML=s.fields.map(fieldHtml).join("");$("#sil-form").dataset.type=type;const d=$("#sil-dialog");d.showModal?d.showModal():d.setAttribute("open","")}
function closeForm(){const d=$("#sil-dialog");d.close?d.close():d.removeAttribute("open")}
function submit(e){e.preventDefault();const type=e.currentTarget.dataset.type,s=schemas[type],data=Object.fromEntries(new FormData(e.currentTarget));if(type==="provider"){state.provider={...state.provider,...data};save();closeForm();return}state.records.unshift({id:uid(),type,category:s.category,title:s.title,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),fields:data,status:/Draft|Pending|Awaiting|Needs/.test(Object.values(data).join(" "))?"Needs confirmation":"Complete"});save();e.currentTarget.reset();closeForm()}
function recordCard(r){const entries=Object.entries(r.fields||{}).filter(([,v])=>v).slice(0,5),risk=r.fields?.risk_level?` sil-risk-${r.fields.risk_level.toLowerCase()}`:"";return`<article class="record${risk}"><div class="record-top"><div><h3>${esc(r.title)}</h3><p>${esc(r.category)} · ${fmt(r.createdAt)}</p></div>${badge(statusOf(r))}</div><p>${entries.map(([k,v])=>`<strong>${esc(k.replaceAll("_"," "))}:</strong> ${esc(v)}`).join("<br>")}</p><div class="sil-record-actions"><button class="link" data-delete="${r.id}">Delete</button></div></article>`}
function render(){const recs=state.records||[],complete=recs.filter(r=>statusOf(r)==="Complete").length,needs=recs.length-complete,houses=recs.filter(r=>r.category==="SIL home").length;
$("#sil-stats").innerHTML=`<div class="stat"><strong>${houses}</strong><span>SIL homes</span></div><div class="stat"><strong>${recs.length}</strong><span>SIL records</span></div><div class="stat"><strong>${complete}</strong><span>Complete</span></div><div class="stat"><strong>${needs}</strong><span>Need attention</span></div>`;
$("#sil-storage-status").textContent="● Records ready";
const outstanding=recs.filter(r=>statusOf(r)!=="Complete");$("#sil-outstanding").innerHTML=outstanding.slice(0,8).map(recordCard).join("")||'<div class="sil-empty">No outstanding SIL records yet. New participant-specific records remain incomplete until confirmed.</div>';
const counts={};recs.forEach(r=>counts[r.category]=(counts[r.category]||0)+1);$("#sil-category-summary").innerHTML=Object.entries(counts).map(([k,v])=>`<article class="record"><div class="record-top"><div><h3>${esc(k)}</h3><p>${v} record${v===1?"":"s"}</p></div></div></article>`).join("")||'<div class="sil-empty">No records have been entered.</div>';
$("#sil-house-list").innerHTML=recs.filter(r=>["SIL home","House safeguarding","Consultation","House governance","Compatibility","Visitors","Conflict of interest"].includes(r.category)).map(recordCard).join("")||'<div class="sil-empty">Add the first SIL home to begin the house file.</div>';
$("#sil-participant-list").innerHTML=recs.filter(r=>["Participant profile","Participant instructions","Supported decision-making","Participant agreement","Housing agreement","Participant rights"].includes(r.category)).map(recordCard).join("")||'<div class="sil-empty">Participant SIL records will appear here.</div>';
$("#sil-shift-list").innerHTML=recs.filter(r=>["Shift handover","Supported decision-making","Visitors"].includes(r.category)).map(recordCard).join("")||'<div class="sil-empty">No SIL shift records.</div>';
$("#sil-worker-list").innerHTML=recs.filter(r=>["Worker induction","Worker competency","Worker training","Practice observation"].includes(r.category)).map(recordCard).join("")||'<div class="sil-empty">No SIL workforce records.</div>';
renderProvider();renderTemplates();renderEvidence();
}
function renderProvider(){const p=state.provider||PROVIDER;$("#sil-provider-profile").innerHTML=`<div class="sil-provider-grid">${Object.entries(p).map(([k,v])=>`<div class="sil-provider-item"><small>${esc(k.replace(/([A-Z])/g," $1"))}</small><strong>${esc(v)}</strong></div>`).join("")}</div>`}
function renderTemplates(){$("#sil-template-register").innerHTML=templates.map(([type,name,review])=>`<article class="record"><div class="record-top"><div><h3>${esc(name)}</h3><p>${esc(type)}</p></div>${badge("Pre-filled template")}</div><div class="sil-template-meta"><span class="badge good">Review: ${esc(review)}</span><span class="badge amber">Signature / participant details when applicable</span></div></article>`).join("")}
function renderEvidence(){const cat=$("#sil-filter-category"),current=cat.value,cats=[...new Set(state.records.map(r=>r.category))].sort();cat.innerHTML='<option value="all">All categories</option>'+cats.map(c=>`<option>${esc(c)}</option>`).join("");cat.value=cats.includes(current)?current:"all";const q=$("#sil-filter-search").value.toLowerCase(),st=$("#sil-filter-status").value,ca=cat.value;const rows=state.records.filter(r=>(ca==="all"||r.category===ca)&&(st==="all"||statusOf(r)===st)&&(!q||JSON.stringify(r).toLowerCase().includes(q)));$("#sil-evidence-list").innerHTML=rows.map(recordCard).join("")||'<div class="sil-empty">No matching evidence records.</div>'}
function exportFile(kind){const rows=state.records.map(r=>({id:r.id,category:r.category,title:r.title,status:statusOf(r),created_at:r.createdAt,...r.fields}));let blob,name;if(kind==="json"){blob=new Blob([JSON.stringify({provider:state.provider,records:rows,exportedAt:new Date().toISOString()},null,2)],{type:"application/json"});name="Florence-SIL-audit-evidence.json"}else{const keys=[...new Set(rows.flatMap(Object.keys))],csv=[keys.join(","),...rows.map(r=>keys.map(k=>'"'+String(r[k]??"").replaceAll('"','""')+'"').join(","))].join("\n");blob=new Blob([csv],{type:"text/csv"});name="Florence-SIL-audit-evidence.csv"}const a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
$$('[data-sil-tab]').forEach(b=>b.onclick=()=>{activeTab=b.dataset.silTab;$$('[data-sil-tab]').forEach(x=>x.classList.toggle("active",x===b));$$('.sil-panel').forEach(x=>x.classList.toggle("active",x.id===`sil-${activeTab}-panel`));if(activeTab==="evidence")renderEvidence()});
$$('[data-open-form]').forEach(b=>b.onclick=()=>openForm(b.dataset.openForm));$("#edit-provider").onclick=()=>{openForm("provider");setTimeout(()=>Object.entries(state.provider||PROVIDER).forEach(([k,v])=>{const e=$(`[name="${k}"]`);if(e)e.value=v}),0)};$("#sil-form").onsubmit=submit;$("#sil-dialog-close").onclick=closeForm;$("#sil-dialog-cancel").onclick=closeForm;$("#sil-refresh").onclick=()=>{state=load();render();toast("SIL workspace refreshed")};$("#sil-export-json").onclick=()=>exportFile("json");$("#sil-export-csv").onclick=()=>exportFile("csv");["#sil-filter-category","#sil-filter-status","#sil-filter-search"].forEach(s=>$(s).addEventListener(s.includes("search")?"input":"change",renderEvidence));document.addEventListener("click",e=>{const b=e.target.closest("[data-delete]");if(!b)return;if(confirm("Delete this SIL record?")){state.records=state.records.filter(r=>r.id!==b.dataset.delete);save()}});
render();
})();
