import "jsr:@supabase/functions-js/edge-runtime.d.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.106.2";

const SUPABASE_URL = Deno.env.get("SUPABASE_URL")!;
const SERVICE_ROLE = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!;
const ORIGIN = "https://i-care-connect.candi1505.workers.dev";
const db = createClient(SUPABASE_URL, SERVICE_ROLE, { auth: { persistSession: false } });
const cors = {"Access-Control-Allow-Origin":ORIGIN,"Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type","Access-Control-Allow-Methods":"POST, OPTIONS"};
const json = (body: unknown, status = 200) => new Response(JSON.stringify(body), { status, headers: { ...cors, "Content-Type":"application/json", "Cache-Control":"no-store" } });
const enc = new TextEncoder(), dec = new TextDecoder();

function clean(name:string){
  let value=(Deno.env.get(name)||"").trim();
  value=value.replace(/^\s*(?:DEPUTY_TOKEN_KEY\s*=\s*)/i,"").trim();
  value=value.replace(/^['"]|['"]$/g,"").replace(/\s+/g,"");
  return value;
}
const TOKEN_KEY=clean("DEPUTY_TOKEN_KEY");
const PERMANENT_TOKEN=(Deno.env.get("DEPUTY_PERMANENT_TOKEN")||"").trim().replace(/^['"]|['"]$/g,"");
const INSTALL_URL=(Deno.env.get("DEPUTY_INSTALL_URL")||"").trim().replace(/^['"]|['"]$/g,"");
function endpoint(){return INSTALL_URL.replace(/^https?:\/\//i,"").replace(/\/$/,"")}
function b64u(bytes:Uint8Array){return btoa(String.fromCharCode(...bytes)).replace(/\+/g,"-").replace(/\//g,"_").replace(/=+$/g,"")}
function unb64(value:string){
  try{
    const n=value.replace(/-/g,"+").replace(/_/g,"/");
    return Uint8Array.from(atob(n+"=".repeat((4-n.length%4)%4)),c=>c.charCodeAt(0));
  }catch{
    throw new Error("DEPUTY_TOKEN_KEY is not valid base64. Replace only its value with the 44-character key copied from PowerShell.");
  }
}
async function cryptoKey(){
  if(!TOKEN_KEY)throw new Error("Missing Supabase secret: DEPUTY_TOKEN_KEY");
  const raw=unb64(TOKEN_KEY);
  if(raw.byteLength!==32)throw new Error(`DEPUTY_TOKEN_KEY decoded to ${raw.byteLength} bytes; it must decode to exactly 32 bytes. Replace only the secret value.`);
  return crypto.subtle.importKey("raw",raw,"AES-GCM",false,["encrypt","decrypt"]);
}
async function encrypt(value:string){const iv=crypto.getRandomValues(new Uint8Array(12));const out=new Uint8Array(await crypto.subtle.encrypt({name:"AES-GCM",iv},await cryptoKey(),enc.encode(value)));return{ciphertext:b64u(out),iv:b64u(iv)}}
async function decrypt(ciphertext:string,iv:string){const out=await crypto.subtle.decrypt({name:"AES-GCM",iv:unb64(iv)},await cryptoKey(),unb64(ciphertext));return dec.decode(out)}
function jwtClaims(token:string):Record<string,unknown>{const part=token.split(".")[1];if(!part)throw new Error("Invalid Florence access token");const base64=part.replace(/-/g,"+").replace(/_/g,"/").padEnd(Math.ceil(part.length/4)*4,"=");const bytes=Uint8Array.from(atob(base64),character=>character.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}
function originAllowed(req:Request){const origin=req.headers.get("Origin");return !origin||origin===ORIGIN}
async function supervisor(req:Request){const auth=req.headers.get("Authorization")||"";if(!auth.startsWith("Bearer "))throw new Error("Sign in to Florence first");const token=auth.slice(7);const {data:u,error:e}=await db.auth.getUser(token);if(e||!u.user)throw new Error("Florence session is not valid");const claims=jwtClaims(token);if(claims.sub!==u.user.id||claims.aal!=="aal2")throw new Error("Multi-factor authentication is required");const {data:p,error}=await db.from("profiles").select("id,organisation_id,role,active").eq("id",u.user.id).single();if(error||!p?.active||p.role!=="supervisor")throw new Error("Only an active Florence supervisor can manage Deputy");return p}
async function callDeputy(path:string,init:RequestInit={},token=PERMANENT_TOKEN){const ep=endpoint();if(!ep)throw new Error("Missing Supabase secret: DEPUTY_INSTALL_URL");if(!token)throw new Error("Missing Supabase secret: DEPUTY_PERMANENT_TOKEN");const res=await fetch(`https://${ep}${path}`,{...init,headers:{Authorization:`Bearer ${token}`,Accept:"application/json","Content-Type":"application/json",...(init.headers||{})}});const text=await res.text();if(!res.ok)throw new Error(`Deputy API ${res.status}: ${text.slice(0,180)||"request failed"}`);if(!text)return null;try{return JSON.parse(text)}catch{return text}}
async function connect(p:any){await cryptoKey();const me=await callDeputy("/api/v1/me");const secured=await encrypt(PERMANENT_TOKEN);const now=new Date().toISOString();const {error}=await db.from("deputy_connections").upsert({organisation_id:p.organisation_id,deputy_endpoint:endpoint(),deputy_user_id:me?.Id!=null?String(me.Id):null,deputy_user_name:me?.DisplayName||me?.Name||me?.FirstName||"Deputy account",access_token_ciphertext:secured.ciphertext,access_token_iv:secured.iv,refresh_token_ciphertext:secured.ciphertext,refresh_token_iv:secured.iv,token_expires_at:"2099-12-31T23:59:59Z",connected_by:p.id,connected_at:now,updated_at:now},{onConflict:"organisation_id"});if(error)throw error;return{connected:true,user_name:me?.DisplayName||me?.Name||null,endpoint:endpoint()}}
async function storedToken(org:string){const {data,error}=await db.from("deputy_connections").select("*").eq("organisation_id",org).maybeSingle();if(error)throw error;if(!data)throw new Error("Connect Deputy before syncing shifts");return{row:data,token:await decrypt(data.access_token_ciphertext,data.access_token_iv)}}
async function apiFor(org:string,path:string,init:RequestInit={}){const {token}=await storedToken(org);return callDeputy(path,init,token)}
async function setupData(p:any){const [employees,areas]=await Promise.all([apiFor(p.organisation_id,"/api/v1/resource/Employee"),apiFor(p.organisation_id,"/api/v1/resource/OperationalUnit")]);const {data:profiles}=await db.from("profiles").select("id,full_name,email,role,active").eq("organisation_id",p.organisation_id).in("role",["staff","supervisor"]).eq("active",true).order("full_name");const {data:mappings}=await db.from("deputy_employee_mappings").select("profile_id,deputy_employee_id,deputy_employee_name,deputy_employee_email").eq("organisation_id",p.organisation_id);const {data:settings}=await db.from("deputy_settings").select("*").eq("organisation_id",p.organisation_id).maybeSingle();return{employees:Array.isArray(employees)?employees:[],areas:Array.isArray(areas)?areas:[],profiles:profiles||[],mappings:mappings||[],settings:settings||null}}
async function saveSetup(p:any,body:any){const areaId=Number(body.area_id);if(!Number.isFinite(areaId))throw new Error("Choose a Deputy area");const maps=Array.isArray(body.mappings)?body.mappings:[];await db.from("deputy_employee_mappings").delete().eq("organisation_id",p.organisation_id);const rows=maps.filter((m:any)=>m.profile_id&&Number.isFinite(Number(m.deputy_employee_id))).map((m:any)=>({organisation_id:p.organisation_id,profile_id:m.profile_id,deputy_employee_id:Number(m.deputy_employee_id),deputy_employee_name:m.deputy_employee_name||null,deputy_employee_email:m.deputy_employee_email||null,matched_by:p.id}));if(rows.length){const {error}=await db.from("deputy_employee_mappings").insert(rows);if(error)throw error}const {error}=await db.from("deputy_settings").upsert({organisation_id:p.organisation_id,deputy_location_id:body.location_id?Number(body.location_id):null,deputy_area_id:areaId,deputy_area_name:body.area_name||null,auto_sync_published:Boolean(body.auto_sync_published),notification_mode:Number(body.notification_mode||5),privacy_label:String(body.privacy_label||"SIL support shift").slice(0,80),updated_by:p.id,updated_at:new Date().toISOString()},{onConflict:"organisation_id"});if(error)throw error;return{saved:true}}
async function locateRoster(org:string,start:number,end:number,employee:number){const payload={search:{s1:{field:"StartTime",data:start,type:"eq"},s2:{field:"EndTime",data:end,type:"eq"},s3:{field:"Employee",data:employee,type:"eq"}}};const result=await apiFor(org,"/api/v1/resource/Roster/QUERY",{method:"POST",body:JSON.stringify(payload)});const list=Array.isArray(result)?result:[];return list[0]?.Id?Number(list[0].Id):null}
async function syncOne(p:any,settings:any,item:any,mapping:any){if(item.status!=="Published")return{status:"skipped",error:"Only published shifts are sent to Deputy"};if(!item.assigned_staff_id)return{status:"skipped",error:"Open shifts wait until a worker is assigned"};if(!mapping)return{status:"failed",error:"Worker is not matched to a Deputy employee"};const start=Math.floor(new Date(item.starts_at).getTime()/1000),end=Math.floor(new Date(item.ends_at).getTime()/1000);const payload:any={intStartTimestamp:start,intEndTimestamp:end,intRosterEmployee:Number(mapping.deputy_employee_id),blnPublish:true,intMealbreakMinute:0,intOpUnitId:Number(settings.deputy_area_id),blnForceOverwrite:0,blnOpen:0,strComment:`${settings.privacy_label||"SIL support shift"} · Florence`,intConfirmStatus:0,intConnectStatus:2};const {data:existing}=await db.from("deputy_shift_syncs").select("deputy_roster_id").eq("shift_id",item.id).maybeSingle();if(existing?.deputy_roster_id)payload.intRosterId=Number(existing.deputy_roster_id);await apiFor(p.organisation_id,"/api/v1/supervise/roster",{method:"POST",body:JSON.stringify(payload)});const rosterId=existing?.deputy_roster_id?Number(existing.deputy_roster_id):await locateRoster(p.organisation_id,start,end,Number(mapping.deputy_employee_id));if(rosterId)await apiFor(p.organisation_id,"/api/v1/supervise/roster/publish",{method:"POST",body:JSON.stringify({intMode:Number(settings.notification_mode||5),blnAllLocationsMode:0,intRosterArray:[rosterId]})});return{status:"synced",rosterId,error:rosterId?null:"Shift created but Deputy did not return its roster ID"}}
async function syncPending(p:any,limit=20){const {data:settings}=await db.from("deputy_settings").select("*").eq("organisation_id",p.organisation_id).maybeSingle();if(!settings?.auto_sync_published)return{synced:0,failed:0,skipped:0,message:"Automatic Deputy sync is not enabled yet"};const {data:queue}=await db.from("deputy_shift_syncs").select("shift_id").eq("organisation_id",p.organisation_id).in("sync_status",["pending","failed"]).order("updated_at").limit(Math.min(50,Math.max(1,Number(limit)||20)));if(!queue?.length)return{synced:0,failed:0,skipped:0,message:"No published shifts are waiting"};const {data:shifts}=await db.from("shifts").select("id,assigned_staff_id,starts_at,ends_at,status").in("id",queue.map((q:any)=>q.shift_id));const {data:maps}=await db.from("deputy_employee_mappings").select("profile_id,deputy_employee_id").eq("organisation_id",p.organisation_id);const map=new Map((maps||[]).map((m:any)=>[m.profile_id,m]));let synced=0,failed=0,skipped=0;for(const shift of shifts||[]){try{const result=await syncOne(p,settings,shift,map.get(shift.assigned_staff_id));if(result.status==="synced")synced++;else if(result.status==="skipped")skipped++;else failed++;await db.from("deputy_shift_syncs").update({deputy_roster_id:result.rosterId||null,sync_status:result.status,last_error:result.error||null,synced_at:result.status==="synced"?new Date().toISOString():null,updated_at:new Date().toISOString()}).eq("shift_id",shift.id)}catch(error){failed++;await db.from("deputy_shift_syncs").update({sync_status:"failed",last_error:error instanceof Error?error.message:"Deputy sync failed",updated_at:new Date().toISOString()}).eq("shift_id",shift.id)}}await db.from("deputy_connections").update({last_synced_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq("organisation_id",p.organisation_id);return{synced,failed,skipped}}

Deno.serve(async(req:Request)=>{if(!originAllowed(req))return json({error:"Request origin is not permitted"},403);if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{if(req.method!=="POST")return json({error:"Unsupported Deputy action"},400);const body=await req.json().catch(()=>({}));const p=await supervisor(req);if(body.action==="start")return json(await connect(p));if(body.action==="status"){const {data:c}=await db.from("deputy_connections").select("deputy_endpoint,deputy_user_name,connected_at,last_synced_at").eq("organisation_id",p.organisation_id).maybeSingle();const {data:s}=await db.from("deputy_settings").select("deputy_area_id,deputy_area_name,auto_sync_published,notification_mode,privacy_label").eq("organisation_id",p.organisation_id).maybeSingle();const {count:pending}=await db.from("deputy_shift_syncs").select("id",{count:"exact",head:true}).eq("organisation_id",p.organisation_id).eq("sync_status","pending");const {count:failed}=await db.from("deputy_shift_syncs").select("id",{count:"exact",head:true}).eq("organisation_id",p.organisation_id).eq("sync_status","failed");return json({connected:Boolean(c),connection:c||null,settings:s||null,pending:pending||0,failed:failed||0})}if(body.action==="setup_data")return json(await setupData(p));if(body.action==="save_setup")return json(await saveSetup(p,body));if(body.action==="sync_pending")return json(await syncPending(p,body.limit));return json({error:"Unsupported Deputy action"},400)}catch(error){console.error("Deputy integration error",error);return json({error:error instanceof Error?error.message:"Deputy integration failed"},400)}});
